### ISSUE TITLE
Hi，the seed didn't work

### ISSUE THREAD

**Issue by magichjm** [simonemarasi/aml-elliptic-gnn#1]
I did four experiments in the same seed,but they got different performance ,the latest like this:
model,Precision,Recall,F1,F1 Micro AVG
- GCN(tx),0.841,0.448,0.585,0.939
- GCN(tx+agg),0.81,0.502,0.62,0.941
- GAT(tx),0.815,0.661,0.73,0.954
- GAT(tx+agg),0.815,0.73,0.77,0.958
- SAGE(tx),0.951,0.77,0.851,0.974
- SAGE(tx+agg),0.934,0.839,0.884,0.979
- Chebyshev(tx),0.955,0.767,0.851,0.974
- Chebyshev(tx+agg),0.95,0.861,0.904,0.982
- GATv2(tx),0.9,0.783,0.838,0.971
- GATv2(tx+agg),0.869,0.863,0.866,0.974

what should I do to match your outcome in that table,thanks

**Comment by simonemarasi** [comment]
Hi, the results you see in the table are the outcome of a single experiment done at the beginning for the paper/report. As you notice, in the current version of the code, you obtain slightly different results (i.e., for the tx and tx+agg model versions). Actually, the results you reported and those you can obtain from the notebook, in the case of tx+agg, are not so different from the ones reported in the table, and in some cases, they are even better!

**Comment by magichjm** [comment]
Oh, I sincerely thank you for your reply. I think I get your meaning. However, the seed setting still seems to be ineffective. I get four different results in four independent experiments.
